### ISSUE TITLE
Cell doesn't need x and y props to be passed to it.

### ISSUE THREAD

**Issue by TomAFrench** [SarahFrench/react-game-of-life#5]
https://github.com/SarahFrench/react-game-of-life/blob/3c0a88fd92d0691124fcc75e10600f3c019f3cb6/src/components/Board.js#L17

You can bake the location of the cell into the `toggleCellState` prop to prevent the cell from needing to know where it is on the board.
```
<Cell key={`cell-${yRowNumber}-${xColumnNumber}`} status={cell} toggleCellState={() => this.props.toggleCellState(xColumnNumber, yRowNumber)} />
```

You'll need to adjust the Cell component to match.

**Comment by SarahFrench** [comment]
Ah yeah! Thanks for this
